github_pat = function(quiet = FALSE) {
  pat <- Sys.getenv("GITHUB_PAT")
  if (nzchar(pat)) {
    if (!quiet) {
      message("Using GitHub PAT from envvar GITHUB_PAT")
    }
    return(pat)
  }
  return(NULL)
}

alval_workflow = function(
  title = "",
  description = "",
  fields = alval_fields(title = title, description = description),
  coverage_type = "coveralls",
  protocol = "https",
  auth_token = NULL,
  ...) {

  r_folder = "R"
  dir.create(r_folder, showWarnings = FALSE, recursive = TRUE)

  man_folder = "man"
  dir.create(man_folder, showWarnings = FALSE, recursive = TRUE)

  usethis::use_git()
  usethis::use_rstudio()
  alval_description(fields = fields)
  ns = paste0("#", " Generated by roxygen2: do not edit by hand\n")
  writeLines(text = ns, con = "NAMESPACE", sep = "")

  # desc = desc::description$new()
  # out = as.list(desc$get(desc$fields()))
  # pack_name = out$Package
  alval_rproj()

  # ".Rproj.user/385142C8/build_options"
#  auto_roxygenize_for_build_and_reload



  usethis::use_readme_rmd(open = FALSE)
  usethis::use_vignette("bad-vignette")
  usethis::use_testthat()

  protocol = match.arg(protocol, choices = c("https", "ssh"))
  if (is.null(auth_token)) {
    auth_token = github_pat()
  }
  if (is.null(auth_token)) {
    if (protocol == "https") {
      stop(paste0(
        "If using GitHub, you need to provide auth_token",
        " or set GITHUB_PAT environment variable")
      )
    }
  }
  try({
  usethis::use_github(
    protocol = protocol,
    auth_token = auth_token,
    ...)
  })

  coverage_type = match.arg(
    coverage_type,
    choices =  c("codecov", "coveralls"))
  usethis::use_appveyor()
  usethis::use_travis(browse = FALSE)
  if (interactive()) {
    utils::browseURL("https://ci.appveyor.com/projects/new")
  }
  usethis::use_coverage(type = coverage_type)

  if (interactive()) {
    res = git2r::config()
    gh_username = res$global$user.name

    coverage_url = switch(
      coverage_type,
      coveralls = "https://coveralls.io/repos/new",
      codecov = paste0("https://codecov.io/gh/", gh_username, "/+")
    )
    utils::browseURL(coverage_url)
  }
  # Want to remove bug fields for Url (not URL)
  desc = desc::description$new()
  desc$del("Url")
  desc$write()

  use_news_md(open = FALSE)

  # res = git2r::config()
  # gh_username = res$global$user.name
  # repo = paste0(gh_username, "/", pack_name)
  travis_cli = Sys.which("travis")
  if (is.null(travis_cli)) {
    have_travis_cli = FALSE
    message("You must")
    head_msg = c("When you do, y")
  } else {
    have_travis_cli = file.exists(travis_cli)
    head_msg = c("Y")
  }
  message(paste0(head_msg,
                 "ou must run travis setup releases",
                 " to setup deployment keys for Travis")
  )

  use_alval_travis(
    coverage_type = coverage_type)

  use_alval_appveyor()
  use_alval_readme_rmd(
    coverage_type = coverage_type)


  invisible(TRUE)
}




